// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pcpjqxuuuawwqxrecexm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjcGpxeHV1dWF3d3F4cmVjZXhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3NjkwOTMsImV4cCI6MjA3MTM0NTA5M30.8foPf8AqHmaux2vTEYM_g8E2EAtIUzFhGE_Uf7Sv4yk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});